name: Build OpenCV

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos-10.15, macos-latest]
        cv_version: [4.5.5, 4.5.4, 4.5.3, 4.5.2, 4.5.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Check threads amount
        run: echo Build with $(nproc) threads ...
      
      - name: Build OpenCV DNN CPU
        run: sh cpu_dnn.sh ${{ matrix.cv_version }}
