name: vcpkg gpu

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'

      - run: echo "Installed cuda version is:${{steps.cuda-toolkit.outputs.cuda}}"

      - run: echo "Cuda install location:${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

      - run: nvcc -V
      
      - uses: actions/checkout@v2
      - name: Build OpenCV DNN GPU on Linux.
        if: runner.os == 'Linux'
        run: |
          echo Building...
          sh with_vcpkg_gpu.sh
