name: Build OpenCV using vcpkg

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
#       - name: List libraries before build.
#         run: ls -lh /usr/local/lib
      
      - name: Build OpenCV DNN CPU on Linux.
        if: runner.os == 'Linux'
        run: |
          echo Building...
          sh with_vcpkg.sh
          
#       - name: List libraries and check build result.
#         run: ls -lh /usr/local/lib | grep opencv
